### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by jcolicchio-soundag** [PengNi/deepsignal-plant#4]
Running call_mods on a mac is giving a NonImplementedError associated with multiprocessing queue.  I have seen elsewhere that Unix machines have an issue with this command and was wondering if there is a work around to get this to run on a Mac machine.  Here is the traceback:

Traceback (most recent call last):
  File "/Users/soundjack/opt/anaconda3/envs/deepsignalpenv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/soundjack/opt/anaconda3/envs/deepsignalpenv/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/soundjack/opt/anaconda3/envs/deepsignalpenv/lib/python3.6/site-packages/deepsignal_plant-0.1.1-py3.6.egg/deepsignal_plant/call_modifications.py", line 251, in _read_features_fast5s_q
    while features_batch_q.qsize() > queen_size_border_f5batch:
  **File "/Users/soundjack/opt/anaconda3/envs/deepsignalpenv/lib/python3.6/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()**

**Comment by jcolicchio-soundag** [comment]
Changed the importing to the following and it worked:

import multiprocessing as mp

# from utils.process_utils import Queue
from .utils.process_utils import Queue

**Comment by PengNi** [comment]
Hi @jcolicchio-soundag , thanks very much for your interest and your debug of deepsignal-plant!

This is actually an unsolved issue between `multiprocess.Queue` and `Mac OS`. Like what you changed, we re-implemented `Queen()` class learned from [vterron's github](https://github.com/vterron/lemon/commit/9ca6b4b1212228dbd4f69b88aaf88b12952d7d6f) to make it work. However, I'm not sure if the self-implemented `Queue()` work with `pytorch in CUDA mode` since I don't have a Mac. So we changed it to `pytorch's implementation`.

I will keep an eye on this, and hope it could be solved perfectly. Thank you again.

Best,
Peng
