### ISSUE TITLE
How important is the basecaller for DeepSignal-Plant?

### ISSUE THREAD

**Issue by shaperones** [PengNi/deepsignal-plant#42]
Hi PengNi,

Thank you for providing this nice and very useful tool!

Could you clarify whether it is possible to use Dorado basecaller results rather than Guppy as input for DeepSignal-Plant (e.g. dna_r9.4.1_e8_fast@v3.4)? As far as I understand, the model was trained on Guppy output and using Dorado (fast / hac / sup models) may potentially differ from what DeepSignal-Plant model expects. Even though mechanically there are no problems and all the tools work well together, I am not sure that using Dorado will not affect the inference of DeepSignal-Plant negatively. 

Also I have seen that DeepSignal3 accepts both Dorado and Guppy as basecallers, but it is not stated how much the specific Dorado model affects the output.

Best regards,
shaperones

**Comment by PengNi** [comment]
Hi @shaperones , 

Thank you for your interest of deepsignal-plant! Different basecallers don't affect the inference of deepsignal-plant significantly. Because deepsignal-plant always needs _re-squiggle_ to map the raw signals to the reference, and according to our tests, sequences generated by different basecallers have similar results of alignment.
However for deepsignal3, we don't recommend other basecallers but Dorado, cause the model of deepginal3 was trained based on the output of specific version of Dorado.

Best,
Peng

**Comment by shaperones** [comment]
Hi PengNi, 

Thank you for the clarification.

All the best,
shaperones
